trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'pipelines-go:$(build.buildId)'

steps:
- task: Docker@2
  displayName: Login to GCR
  inputs:
    command: login
    containerRegistry: GoogleContainerRegistryQA
- task: Docker@2
  displayName: 'Docker build'
  inputs:
    command: build
    tags: $(imageName)

- task: Docker@2
  displayName: Push image to GCR
  inputs:
    command: push
    repository: $(imageName)
    tags: $(build.buildId)

- task: Docker@2
  displayName: Logout from GCR
  inputs:
    command: Logout
    containerRegistry: GoogleContainerRegistryQA