trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'powerchord-qa/pipelines-go'

steps:
- task: Docker@2
  displayName: Login to GCR
  inputs:
    command: login
    containerRegistry: GoogleContainerRegistryQA
- task: Docker@2
  displayName: 'Docker build'
  inputs:
    command: build
    repository: $(imageRepository)
    tags: $(build.buildId)

- task: Docker@2
  displayName: Push image to GCR
  inputs:
    command: push
    repository: $(imageRepository)
    tags: $(build.buildId)

- task: Docker@2
  displayName: Logout from GCR
  inputs:
    command: Logout
    containerRegistry: GoogleContainerRegistryQA


- task: GitHubRelease@1
  displayName: Github Release
  inputs:
    gitHubConnection: 'acheraimeHub'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    releaseNotesSource: 'inline'
    tag: '$(Build.BuildNumber)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'